### ISSUE TITLE
Error:	Wrong number of args

### ISSUE THREAD

**Issue by jaberio** [bug3/installer#1]
i had an issue when i try to uninstall the project from my ubuntu ,

it says Wrong number of args 

ash <(wget -qO- dar.vin/install) $userName $repository $branch -r
Error:	Wrong number of args

**Comment by bug3** [comment]
Hello @JaberQayad thank you for pointing out this issue. When you set it as default (  $userName, $repository $branch  ) it gives this error. For example: `bash <(wget -qO- dar.vin/install) bug3 autoclear`
